name: C/Build

on: [push]

jobs:      
  job_build:
    name: File2Image Build
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        make
        make clean
    - name: list_commands
      run: ./File2Image -v
